clear all
close all
clc

%% create a GUI window
window = figure('position',[0,0,500,400],...
        'unit','pixels',... % set figure unit to pixels
        'name','GUIversion',...% set figure name to "GUIversion"
        'visible','on',...  % set figure visiblity
        'NumberTitle','off'); % turn off shown 'Figure1'
movegui(window,'center'); % move figure to the center of the windows

%% create cells
CornerX = 120;
CornerY = 270;
dx = 50;
dy = 50;
for rows = 1:2
    for cols = 1:5
        xPos = CornerX + (cols-1)*dx;
        yPos = CornerY - (rows-1)*dy;
        GUIversion.X(rows,cols) = uicontrol('unit','pixels',...
                                        'background','w',...
                                        'Style','edit',...
                                        'visible','on',...
                                        'position',[xPos,yPos,dx,dy],...
                                        'fontsize',14,...
                                        'fontweight','normal',...
                                        'enable','on',...
                                        'KeyPressFcn',{@cbEntry,window,rows,cols});
                                        
    end
end

%% insert a title textbox
GUIversion.title = uicontrol('Style','text',...
                            'unit','pixels',...
                            'Fontweight','normal',...
                            'string','Duncan Version Game',...
                            'Position',[70 360 350 30],...
                            'FontSize',15,...
                            'backgroundcolor',[0.5 0.8 0.1],...
                            'foregroundcolor',[0.2 0.5 1]);
%% insert a check buttom
GUIversion.check = uicontrol('style','pushbutton',...
                            'callback',{@cbCheck,window},...
                            'string','CHECK',...
                            'position',[120,175,100,30],...
                            'backgroundcolor',[0.2 0 0.7],...
                            'foregroundcolor',[0.2 0.9 0]);
%% insert a rewrite buttom
GUIversion.rewrite = uicontrol('style','pushbutton',...
                            'callback',{@cbRewrite,window},...
                            'string','REWRITE',...
                            'position',[270,175,100,30],...
                            'backgroundcolor',[0.9 0.1 0.2],...
                            'foregroundcolor',[1 0.9 0]);
%% insert a rule buttom
GUIversion.rewrite = uicontrol('style','pushbutton',...
                            'callback',{@cbRules,window},...
                            'string','RULE',...
                            'position',[205,325,80,30],...
                            'backgroundcolor',[0.1 0.1 0.2],...
                            'foregroundcolor',[1 1 0]);
%% insert a status bar                        
GUIversion.status = uicontrol('style','text',...
                              'unit','pixels',...
                              'string','The goal of that game is to fill a board of 2 rows and 2018 columns with zeros and ones so that two equal numers in two adjacent cells of the same  row prevent the use of two equal numbers on the corresponding cells of the other row. Hit CHECK to check your result.Or, Hit REWRITE to rewrite your board!',...
                              'position',[25,15,450,150],...
                              'backgroundcolor',[0.7 0.8 0.7],...
                              'Fontsize',12,...
                              'Horizontalalignment','center');
% this line using set function to set the object property
set(window,'UserData',GUIversion);